version: '2'
services:
  user_storage:
    image: mongo
  user_service:
    build: user_service
    volumes:
     - ./user_service:/usr/src/app
    links:
     - user_storage
  website:
    build: website
    volumes:
     - ./website:/usr/src/app
    links:
     - user_service

  reverse_proxy:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/logs:/etc/nginx/logs
    links:
     - user_service
     - website
